version: '3.8'

services:
  openhands:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - LETTA_BASE_URL=https://letta2.oculair.ca
      - LETTA_AGENT_ID=${LETTA_AGENT_ID}
      - LETTA_PASSWORD=${LETTA_PASSWORD}
      - DEBUG=true  # Enable debug logging
    volumes:
      # Mount workspace for development (optional)
      - ../../../workspace:/openhands/workspace
    restart: unless-stopped