version: '3.8'

services:
  openhands-api:
    image: oculair/openhandsapi:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - openhands-network

networks:
  openhands-network:
    driver: bridge